# Файл docker-compose.yml
#version: '3.5'
# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер селеноида
  selenoid:
    # Из какого образа запустить контейнер:
    image: "aerokube/selenoid"
    # Как назвать контейнер:
    container_name: selenoid
    # Порты для работы:
    ports:
      - "4444:4444"
    # Настройка сети для взаимодействия контейнеров
    networks:
      - selenoid
    # Какой volume подключить для этого контейнера
    volumes:
      - "./selenoid/browsers.json:/etc/selenoid/browsers.json:ro"    #тут должен лежать browsers.json с настройками браузера
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-container-network", "selenoid"]

  # Имя и описание контейнера ui для селеноида
  selenoid-ui:
    image: "aerokube/selenoid-ui:latest"
    container_name: selenoid-ui
    links:
      - selenoid
    ports:
      - "8081:8080"
    networks:
      - selenoid
    command: ["--selenoid-uri", "http://selenoid:4444"]

  test:
    build: .
    container_name: test_docker
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - selenoid
    networks:
      - selenoid
    tty: true
    environment:
      SELENOID_URI: http://selenoid:4444/wd/hub
      BROWSER: chrome
      BROWSER_VERSION: 128.0
    volumes:
      - ./reports:/app/reports
    command: ["pytest", "-v", "--alluredir=reports/allure-results"]

  networks:
    selenoid:
    name: selenoid